### PR TITLE
add support for 9223:9222 port mapping

### PR DESCRIPTION
**Pull request by matthewmueller**
This PR adds support for passing a port mapping into `Expose` like this:

```go
conf := &conex.Config{
	Image:  Image,
	Expose: []string{"9333:9222/udp"},
}
```

This is a non-breaking change, so if you do: 

```go
conf := &conex.Config{
	Image:  Image,
	Expose: []string{"9222"},
}
```

It'll work as before.

### CODE REVIEW

**Comment by omeid** [comment]
I will review this later, but could you please tell me why would you want to bind to the host? This will create problems with concurrent tests as they might all fight for the same port.

**Comment by omeid** [comment]
I see this would be useful with _Docker for Mac_.

**Comment by matthewmueller** [comment]
Hah maybe I'm missing another way, but it's actually to allow you to run multiple containers in parallel. Right now if you want to run the tests they need to run serially since multiple tests cannot connect on 1 port, but perhaps if the addresses are all different and I can connect to them locally, this wouldn't be a problem. Perhaps this would be solved by #5 


I'm using this function to find a free port on the host:

```go

// get an available port
func findPort() (int, error) {
	addr, err := net.ResolveTCPAddr("tcp", "localhost:0")
	if err != nil {
		return 0, err
	}

	l, err := net.ListenTCP("tcp", addr)
	if err != nil {
		return 0, err
	}
	defer l.Close()

	return l.Addr().(*net.TCPAddr).Port, nil
}
```

**Comment by omeid** [comment]
Nope. When you call `conex.Box` (or conex.Manager.Box), you actually get a new container every time you call it. So the address of the box changes. Please read the whole readme :)

**Comment by matthewmueller** [comment]
Ah yah, I knew that. But right now multiple containers on 1 port doesn't do much good (locally) since you can't use connect to the host given by `container.Address()`. So this PR allows you to have multiple containers running on multiple ports with one host (`127.0.0.1`). But yah, this is unnecessary locally if #5 can be resolved.

**Comment by omeid** [comment]
Sorry @matthewmueller, I am going to close this for now as no one else has expressed interest or we have found a simple solution. If you still need this, feel free to reopen the issue.

**Pull request closed without merging**
